In [42]:
import numpy as np
import pandas as pd
import math

train = pd.read_csv('crime-train.txt',delimiter='\t')
test = pd.read_csv('crime-test.txt', delimiter='\t')
print("Training dataset:")
train.head()

Training dataset:

,ViolentCrimesPerPop,population,householdsize,agePct12t21,agePct12t29,agePct16t24,agePct65up,numbUrban,pctUrban,medIncome,...,NumStreet,PctForeignBorn,PctBornSameState,PctSameHouse85,PctSameCity85,PctSameState85,LandArea,PopDens,PctUsePubTrans,LemasPctOfficDrugUn
0,0.67,-0.45,-1.85,-1.06,0.67,0.08,-0.85,-0.34,0.68,-0.24,...,-0.23,-0.02,-0.53,-1.08,-0.13,-0.66,-0.41,-0.56,1.26,-0.39
1,0.43,-0.45,-0.27,-0.22,-0.17,-0.34,-0.58,-0.50,-1.57,-0.29,...,-0.23,-0.33,-0.58,0.03,0.22,-0.46,-0.50,-0.11,-0.62,-0.39
2,0.12,-0.14,1.87,0.55,0.04,0.02,-1.19,-0.03,0.68,1.05,...,-0.23,-0.11,-1.51,1.07,0.07,-0.01,-0.41,0.77,0.52,-0.39
3,0.03,-0.38,0.53,-0.28,-0.79,-0.64,-0.35,-0.34,0.46,0.66,...,-0.23,-0.46,0.54,0.58,-0.08,-0.61,-0.23,-0.70,-0.62,-0.39
4,0.14,-0.30,-1.12,-0.74,-0.10,-0.40,-0.30,-0.19,0.68,0.76,...,-0.23,2.10,-0.92,-0.25,0.52,-0.06,-0.50,1.71,-0.27,-0.39

In [43]:
X_train = train.drop('ViolentCrimesPerPop',axis=1)
y_train = train['ViolentCrimesPerPop']

X_train = np.float64(X_train)
y_train = np.float64(y_train)

X_train = np.column_stack((X_train, np.ones(len(X_train))))
y_train = np.reshape(y_train, (-1,1))


#do the same with test


X_test = test.drop('ViolentCrimesPerPop',axis=1)
y_test = test['ViolentCrimesPerPop']

X_test = np.float64(X_test)
y_test = np.float64(y_test)


X_test = np.column_stack((X_test, np.ones(len(X_test))))
y_test = np.reshape(y_test, (-1,1))

In [44]:
def LinRegression(X,y):
    w_l = np.matmul(np.matmul(np.linalg.inv(np.matmul(np.transpose(X), X)), np.transpose(X)), y)
    y_hat = np.matmul(X,w_l)
    return y_hat

In [45]:
def MSE(y_hat, y):
    return ((y_hat-y)**2).sum()/len(y)

y_hat = LinRegression(X_train,y_train)
y_tst_hat = LinRegression(X_test, y_test)
print("linear regression: training err={:.3f}, testing err={:.3f}".format(mse(y_hat,y_train), mse(y_tst_hat, y_test)))

linear regression: training err=0.016, testing err=0.015

In [46]:
def linear_gradient_descent(x, y, w):
    left = (y - np.dot(x, w)).T
    right = (y - np.dot(x, w))
    min_w = np.dot(left, right)
    return min_w

In [47]:
alpha = 1*(10**-5)

L1 = 1
L0 = 0
w0 = np.random.normal(0, 1, (X_train.shape[1],1))
while (abs(L1 - L0) > (10**-5)):
    w1 = w0 - (alpha * np.dot(X_train.T, (np.dot(X_train, w0) - y_train)))
    L0 = linear_gradient_descent(X_train, y_train, w0)
    L1 = linear_gradient_descent(X_train, y_train, w1)
    
    w0 = w1

In [48]:
def problem2(samples):
    prediction = []
    for x in samples:
        prediction.append(np.dot(w0.T, x))
    return prediction

In [50]:
train_prediction = []
test_prediction = []

train_prediction = problem2(X_train)

train_linear_MSE = MSE(train_prediction, y_train)


test_prediction = problem2(X_test)

test_linear_MSE = MSE(test_prediction, y_test)


print("Training MSE for linear regression using gradient descent is", train_linear_MSE)

print("Testing MSE for linear regression using gradient descent is", test_linear_MSE)

print("linear regression: training err=21.779, testing err=48.629")

Training MSE for linear regression using gradient descent is 0.01649917686669319
Testing MSE for linear regression using gradient descent is 0.02098848666987729
linear regression: training err=21.779, testing err=48.629